# Generated by Django 4.1.7 on 2023-07-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chollo_cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
